name = "duckly-scrollytelling"
account_id = "c12bce427a48c6bab79e16bfddbcaa2f"
compatibility_date = "2026-04-30"
main = "./worker.js"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true
