name = "duckly-scrollytelling"
account_id = "7722052fdf1845b1b5e987938bb735f3"
compatibility_date = "2026-04-30"
main = "./worker.js"
workers_dev = false

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true

[[d1_databases]]
binding = "FEEDBACK_DB"
database_name = "resume-feedback"
database_id = "a1234648-7657-441a-9cf8-0982503e6786"

[ai]
binding = "AI"
